# Generated by Django 5.0.4 on 2025-04-16 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_location', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=100)),
                ('goods_type', models.CharField(max_length=100)),
                ('quantity', models.FloatField(help_text='In tons or units')),
                ('required_date', models.DateField()),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
