# Generated by Django 5.2.4 on 2025-08-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_load_delete_loadrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
