# Generated by Django 5.0.4 on 2025-04-14 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('driving_experience', models.PositiveIntegerField(help_text='Experience in years')),
                ('vehicle_type', models.CharField(blank=True, help_text='E.g., Truck, Lorry, Container', max_length=50, null=True)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='drivers/profile_pics/')),
                ('address', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('current_location', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
